--- 
- name: Deploy
  hosts: all
  become: true
  vars_files:
    - tomcat_credentials.yml 
  tasks: 
  - name: Tomcat
    command: curl -v -u "{{ user_name }}":"{{ password }}" -T /home/ubuntu/actions-runner/_work/ansible_tomcat/ansible_tomcat/target/WebApp-pipeline.war "http://15.207.100.78:8080//manager/text/deploy?path=/web_rutu&update=true"
